[96] Fix Basic-GetFeature-tc4 problems
opengeospatial/ets-wfs11 pull request #97
Opened 2022-11-30 18:16 UTC by davidblasby

See https://github.com/opengeospatial/ets-wfs11/issues/96

I found two problems with the "wfs:wfs-1.1.0-Basic-GetFeature-tc4" test.

1. (line 525 - request2) Request2 has the `service=` parameter missing in the URL.  However, the test case was checking for a missing `request=`.  Likely a copy-and-paste mistake.

2. (line 540 - request3). Request3 has the `version=` parameter missing in the URL.  The test was, incorrectly, looking for a missing `request=` (as above).  Also, in OGC systems where there are multiple WFS Versions running (i.e. wfs 1.1.0 and wfs 2.0), the ExceptionReport could be of different versions (i.e. a WFS 2.0 ExceptionReport).  This wasn't validating.  I've changed the test so it just looks for "ExceptionReport" text in the response.
Please see the [issue report specific to this problem](https://github.com/opengeospatial/ets-wfs11/issues/96) as well as [similar, older, reports](https://github.com/opengeospatial/ets-wfs11/issues/66).

2022-11-30 19:20 UTC, davidblasby commented
FYI: I am currently trying to get Geoserver to pass CITE tests.

https://osgeo-org.atlassian.net/jira/software/c/projects/GEOS/issues/GEOS-10764

2023-01-19 09:33 UTC, bpross-52n approved these changes

2023-01-25 13:32 UTC, dstenger requested changes

2023-01-25 13:32 UTC, dstenger commented on src/main/scripts/ctl/basic/GetFeature/GetFeature-GET.xml
> +          <xsl:if test="not(contains($request3, 'version')">
Closing `)` is missing.

2023-01-25 13:53 UTC, davidblasby commented
Added ")" and changed it to check for "ExceptionReport" in the test.

2023-01-26 09:44 UTC, dstenger approved these changes

2023-01-26 09:46 UTC, merged

2023-01-26 14:16 UTC, dstenger commented
A further fix had to be done for the implementation of request3 as contains() just detects values of elements but not the elements itself.

Commit (directly on master branch as this pull request is already merged): https://github.com/opengeospatial/ets-wfs11/commit/7a98651e05a2f6a3ab7a001179ee3a0f61d72337